apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockalert
  namespace: stockalert
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stockalert
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: stockalert
    spec:
      containers:
      - name: api
        image: hotweels94/stockalert:v1.0.1
        ports:
        - containerPort: 3000
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: stockalert-secret
              key: API_KEY
        readinessProbe:
          httpGet:
            command:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
